# -*- coding: utf-8 -*-
"""给已生成的图纸/方案管理字段补上 pickable_scope。"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

PERSON_SCOPE = {
    "scope_code": "room_leaders",
    "filter_by_fields": ["offices", "offices_multi"],
}
OFFICE_SCOPE = {"scope_code": "scheme_offices"}
PERSON_IDS = frozenset({"design_assignees", "designer"})
OFFICE_IDS = frozenset({"offices", "offices_multi"})


def patch_fields(fields: list) -> int:
    n = 0
    for fd in fields or []:
        if not isinstance(fd, dict) or not fd.get("id"):
            continue
        fid = fd["id"]
        if fid in PERSON_IDS:
            props = dict(fd.get("props") or {})
            props["pickable_scope"] = dict(PERSON_SCOPE)
            fd["props"] = props
            if fid == "design_assignees" and fd.get("type") == "person":
                fd["type"] = "person_multi"
            n += 1
        elif fid in OFFICE_IDS:
            props = dict(fd.get("props") or {})
            props["pickable_scope"] = dict(OFFICE_SCOPE)
            fd["props"] = props
            n += 1
    return n


def rewrite_drawing():
    path = ROOT / "app" / "domains" / "lowcode" / "_drawing_jdy_generated.py"
    from app.domains.lowcode._drawing_jdy_generated import DRAWING_JDY
    data = json.loads(json.dumps(DRAWING_JDY, ensure_ascii=False))
    total = 0
    for form in data.values():
        total += patch_fields(form.get("field_definitions") or [])
    blob = json.dumps(data, ensure_ascii=False)
    path.write_text(
        "# Auto-generated by scripts/_gen_drawing_jdy.py — DO NOT EDIT BY HAND\n"
        "# Patched pickable_scope: design_assignees/designer + offices.\n"
        "import json\n\n"
        f"DRAWING_JDY = json.loads(r'''{blob}''')\n",
        encoding="utf-8",
    )
    return total


def rewrite_scheme():
    path = ROOT / "app" / "domains" / "lowcode" / "_scheme_management_generated.py"
    from app.domains.lowcode._scheme_management_generated import SCHEME_MANAGEMENT_JDY
    data = json.loads(json.dumps(SCHEME_MANAGEMENT_JDY, ensure_ascii=False))
    total = 0
    for form in data.values():
        total += patch_fields(form.get("field_definitions") or [])
    blob = json.dumps(data, ensure_ascii=False)
    path.write_text(
        "# Auto-generated by scripts/_gen_scheme_management.py — DO NOT EDIT BY HAND\n"
        "# Patched pickable_scope: design_assignees/designer + offices.\n"
        "import json\n\n"
        f"SCHEME_MANAGEMENT_JDY = json.loads(r'''{blob}''')\n",
        encoding="utf-8",
    )
    return total


if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(ROOT))
    print("drawing", rewrite_drawing())
    print("scheme", rewrite_scheme())
