"""add_enriched_fields

Revision ID: 116a971e52b1
Revises: bec0cd8c2dec
Create Date: 2026-02-27 22:03:10.488541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116a971e52b1'
down_revision: Union[str, None] = 'bec0cd8c2dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('audit_logs', sa.Column('trace_id', sa.String(length=36), nullable=True))
    op.add_column('contacts', sa.Column('role_type', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('customer_code', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('scale_level', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('website', sa.String(length=300), nullable=True))
    op.add_column('customers', sa.Column('tags_json', sa.JSON(), nullable=True))
    op.add_column('leads', sa.Column('contact_raw_json', sa.JSON(), nullable=True))
    op.add_column('leads', sa.Column('source_detail_json', sa.JSON(), nullable=True))
    op.add_column('leads', sa.Column('demand_summary', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('budget_range', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'budget_range')
    op.drop_column('leads', 'demand_summary')
    op.drop_column('leads', 'source_detail_json')
    op.drop_column('leads', 'contact_raw_json')
    op.drop_column('customers', 'tags_json')
    op.drop_column('customers', 'website')
    op.drop_column('customers', 'scale_level')
    op.drop_column('customers', 'customer_code')
    op.drop_column('contacts', 'role_type')
    op.drop_column('audit_logs', 'trace_id')
    op.drop_column('audit_logs', 'user_agent')
    # ### end Alembic commands ###
