"""add_from_quote_id_to_contracts

Revision ID: 4309d75755b8
Revises: c0d74316a046
Create Date: 2026-02-28 17:32:41.867212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4309d75755b8'
down_revision: Union[str, None] = 'c0d74316a046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('from_quote_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_contracts_from_quote_id'), 'contracts', ['from_quote_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_from_quote_id'), table_name='contracts')
    op.drop_column('contracts', 'from_quote_id')
    # ### end Alembic commands ###
