"""add_admin_console_tables

Revision ID: 73c17709cda6
Revises: f7d05d597e85
Create Date: 2026-02-28 13:50:13.667558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c17709cda6'
down_revision: Union[str, None] = 'f7d05d597e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_endpoints',
    sa.Column('system_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('auth_type', sa.String(length=32), nullable=True),
    sa.Column('auth_config_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_endpoints_system_code'), 'integration_endpoints', ['system_code'], unique=False)
    op.create_index(op.f('ix_integration_endpoints_tenant_id'), 'integration_endpoints', ['tenant_id'], unique=False)
    op.create_table('margin_policies',
    sa.Column('policy_code', sa.String(length=64), nullable=False),
    sa.Column('scope_json', sa.JSON(), nullable=True),
    sa.Column('redline_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_margin_policies_tenant_id'), 'margin_policies', ['tenant_id'], unique=False)
    op.create_table('stage_definitions',
    sa.Column('stage_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('allowed_transitions_json', sa.JSON(), nullable=True),
    sa.Column('gate_rules_json', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_definitions_stage_code'), 'stage_definitions', ['stage_code'], unique=False)
    op.create_index(op.f('ix_stage_definitions_tenant_id'), 'stage_definitions', ['tenant_id'], unique=False)
    op.create_table('tenant_ai_budgets',
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('budget_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('used_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('budget_tokens', sa.Integer(), nullable=True),
    sa.Column('used_tokens', sa.Integer(), nullable=True),
    sa.Column('hard_limit', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_ai_budgets_tenant_id'), 'tenant_ai_budgets', ['tenant_id'], unique=False)
    op.create_table('tenant_ai_policies',
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('model_route_json', sa.JSON(), nullable=True),
    sa.Column('budget_json', sa.JSON(), nullable=True),
    sa.Column('trigger_json', sa.JSON(), nullable=True),
    sa.Column('guardrails_json', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_ai_policies_task_type'), 'tenant_ai_policies', ['task_type'], unique=False)
    op.create_index(op.f('ix_tenant_ai_policies_tenant_id'), 'tenant_ai_policies', ['tenant_id'], unique=False)
    op.create_table('tenant_feature_toggles',
    sa.Column('feature_code', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_feature_toggles_feature_code'), 'tenant_feature_toggles', ['feature_code'], unique=False)
    op.create_index(op.f('ix_tenant_feature_toggles_tenant_id'), 'tenant_feature_toggles', ['tenant_id'], unique=False)
    op.create_table('tenant_plans',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pricing_json', sa.JSON(), nullable=True),
    sa.Column('limits_json', sa.JSON(), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_profiles',
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('logo_attachment_id', sa.String(length=36), nullable=True),
    sa.Column('security_policy_json', sa.JSON(), nullable=True),
    sa.Column('data_retention_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_profiles_tenant_id'), 'tenant_profiles', ['tenant_id'], unique=False)
    op.create_table('tenant_usage_meters',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_usage_meters_tenant_id'), 'tenant_usage_meters', ['tenant_id'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('event_types_json', sa.JSON(), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('secret_token', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_subscriptions_tenant_id'), 'webhook_subscriptions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_subscriptions_tenant_id'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index(op.f('ix_tenant_usage_meters_tenant_id'), table_name='tenant_usage_meters')
    op.drop_table('tenant_usage_meters')
    op.drop_index(op.f('ix_tenant_profiles_tenant_id'), table_name='tenant_profiles')
    op.drop_table('tenant_profiles')
    op.drop_table('tenant_plans')
    op.drop_index(op.f('ix_tenant_feature_toggles_tenant_id'), table_name='tenant_feature_toggles')
    op.drop_index(op.f('ix_tenant_feature_toggles_feature_code'), table_name='tenant_feature_toggles')
    op.drop_table('tenant_feature_toggles')
    op.drop_index(op.f('ix_tenant_ai_policies_tenant_id'), table_name='tenant_ai_policies')
    op.drop_index(op.f('ix_tenant_ai_policies_task_type'), table_name='tenant_ai_policies')
    op.drop_table('tenant_ai_policies')
    op.drop_index(op.f('ix_tenant_ai_budgets_tenant_id'), table_name='tenant_ai_budgets')
    op.drop_table('tenant_ai_budgets')
    op.drop_index(op.f('ix_stage_definitions_tenant_id'), table_name='stage_definitions')
    op.drop_index(op.f('ix_stage_definitions_stage_code'), table_name='stage_definitions')
    op.drop_table('stage_definitions')
    op.drop_index(op.f('ix_margin_policies_tenant_id'), table_name='margin_policies')
    op.drop_table('margin_policies')
    op.drop_index(op.f('ix_integration_endpoints_tenant_id'), table_name='integration_endpoints')
    op.drop_index(op.f('ix_integration_endpoints_system_code'), table_name='integration_endpoints')
    op.drop_table('integration_endpoints')
    # ### end Alembic commands ###
