"""add_customer_relations_and_acl_shares

Revision ID: 84f6130693d9
Revises: 45d269685508
Create Date: 2026-02-28 14:39:00.695885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f6130693d9'
down_revision: Union[str, None] = '45d269685508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acl_shares',
    sa.Column('biz_type', sa.String(length=64), nullable=False),
    sa.Column('biz_id', sa.String(length=36), nullable=False),
    sa.Column('shared_to_type', sa.String(length=16), nullable=False),
    sa.Column('shared_to_id', sa.String(length=36), nullable=False),
    sa.Column('shared_to_name', sa.String(length=100), nullable=True),
    sa.Column('permission', sa.String(length=16), nullable=False),
    sa.Column('shared_by_id', sa.String(length=36), nullable=True),
    sa.Column('shared_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acl_shares_biz_id'), 'acl_shares', ['biz_id'], unique=False)
    op.create_index(op.f('ix_acl_shares_biz_type'), 'acl_shares', ['biz_type'], unique=False)
    op.create_index(op.f('ix_acl_shares_tenant_id'), 'acl_shares', ['tenant_id'], unique=False)
    op.create_table('customer_relations',
    sa.Column('from_customer_id', sa.String(length=36), nullable=False),
    sa.Column('to_customer_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_relations_from_customer_id'), 'customer_relations', ['from_customer_id'], unique=False)
    op.create_index(op.f('ix_customer_relations_tenant_id'), 'customer_relations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_customer_relations_to_customer_id'), 'customer_relations', ['to_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_relations_to_customer_id'), table_name='customer_relations')
    op.drop_index(op.f('ix_customer_relations_tenant_id'), table_name='customer_relations')
    op.drop_index(op.f('ix_customer_relations_from_customer_id'), table_name='customer_relations')
    op.drop_table('customer_relations')
    op.drop_index(op.f('ix_acl_shares_tenant_id'), table_name='acl_shares')
    op.drop_index(op.f('ix_acl_shares_biz_type'), table_name='acl_shares')
    op.drop_index(op.f('ix_acl_shares_biz_id'), table_name='acl_shares')
    op.drop_table('acl_shares')
    # ### end Alembic commands ###
