"""add_solution_tables

Revision ID: 92cc5acb5633
Revises: e4bb22e47034
Create Date: 2026-02-27 23:49:41.158537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92cc5acb5633'
down_revision: Union[str, None] = 'e4bb22e47034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution_versions',
    sa.Column('solution_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('risk_list_json', sa.JSON(), nullable=True),
    sa.Column('ai_insights_json', sa.JSON(), nullable=True),
    sa.Column('doc_attachment_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_versions_solution_id'), 'solution_versions', ['solution_id'], unique=False)
    op.create_index(op.f('ix_solution_versions_tenant_id'), 'solution_versions', ['tenant_id'], unique=False)
    op.create_table('solutions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('solution_no', sa.String(length=64), nullable=False),
    sa.Column('current_version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_project_id'), 'solutions', ['project_id'], unique=False)
    op.create_index(op.f('ix_solutions_tenant_id'), 'solutions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solutions_tenant_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_project_id'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_solution_versions_tenant_id'), table_name='solution_versions')
    op.drop_index(op.f('ix_solution_versions_solution_id'), table_name='solution_versions')
    op.drop_table('solution_versions')
    # ### end Alembic commands ###
