"""add_activity_and_ai_center_tables

Revision ID: b946314d27fb
Revises: ba8898109ef3
Create Date: 2026-02-28 11:56:51.370239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b946314d27fb'
down_revision: Union[str, None] = 'ba8898109ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('biz_type', sa.String(length=32), nullable=False),
    sa.Column('biz_id', sa.String(length=36), nullable=False),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_biz_id'), 'activities', ['biz_id'], unique=False)
    op.create_index(op.f('ix_activities_biz_type'), 'activities', ['biz_type'], unique=False)
    op.create_index(op.f('ix_activities_tenant_id'), 'activities', ['tenant_id'], unique=False)
    op.create_table('ai_prompt_templates',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=True),
    sa.Column('output_schema_json', sa.JSON(), nullable=True),
    sa.Column('guardrails_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_prompt_templates_code'), 'ai_prompt_templates', ['code'], unique=False)
    op.create_index(op.f('ix_ai_prompt_templates_task_type'), 'ai_prompt_templates', ['task_type'], unique=False)
    op.create_index(op.f('ix_ai_prompt_templates_tenant_id'), 'ai_prompt_templates', ['tenant_id'], unique=False)
    op.create_table('ai_results',
    sa.Column('ai_task_id', sa.String(length=36), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=2), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_results_ai_task_id'), 'ai_results', ['ai_task_id'], unique=False)
    op.create_index(op.f('ix_ai_results_tenant_id'), 'ai_results', ['tenant_id'], unique=False)
    op.create_table('ai_tasks',
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('biz_type', sa.String(length=32), nullable=True),
    sa.Column('biz_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_template_id', sa.String(length=36), nullable=True),
    sa.Column('input_ref_json', sa.JSON(), nullable=True),
    sa.Column('budget_json', sa.JSON(), nullable=True),
    sa.Column('token_in', sa.Integer(), nullable=True),
    sa.Column('token_out', sa.Integer(), nullable=True),
    sa.Column('cost_est', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tasks_biz_id'), 'ai_tasks', ['biz_id'], unique=False)
    op.create_index(op.f('ix_ai_tasks_status'), 'ai_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_ai_tasks_task_type'), 'ai_tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_ai_tasks_tenant_id'), 'ai_tasks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tasks_tenant_id'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_task_type'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_status'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_biz_id'), table_name='ai_tasks')
    op.drop_table('ai_tasks')
    op.drop_index(op.f('ix_ai_results_tenant_id'), table_name='ai_results')
    op.drop_index(op.f('ix_ai_results_ai_task_id'), table_name='ai_results')
    op.drop_table('ai_results')
    op.drop_index(op.f('ix_ai_prompt_templates_tenant_id'), table_name='ai_prompt_templates')
    op.drop_index(op.f('ix_ai_prompt_templates_task_type'), table_name='ai_prompt_templates')
    op.drop_index(op.f('ix_ai_prompt_templates_code'), table_name='ai_prompt_templates')
    op.drop_table('ai_prompt_templates')
    op.drop_index(op.f('ix_activities_tenant_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_biz_type'), table_name='activities')
    op.drop_index(op.f('ix_activities_biz_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
