"""add_delivery_payment_change_service_tables

Revision ID: ba8898109ef3
Revises: 92cc5acb5633
Create Date: 2026-02-28 00:08:58.001628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8898109ef3'
down_revision: Union[str, None] = '92cc5acb5633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_requests',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('change_no', sa.String(length=64), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('from_version_ref_json', sa.JSON(), nullable=True),
    sa.Column('to_version_ref_json', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('impact_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_requests_project_id'), 'change_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_change_requests_tenant_id'), 'change_requests', ['tenant_id'], unique=False)
    op.create_table('delivery_milestones',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('plan_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_milestones_project_id'), 'delivery_milestones', ['project_id'], unique=False)
    op.create_index(op.f('ix_delivery_milestones_tenant_id'), 'delivery_milestones', ['tenant_id'], unique=False)
    op.create_table('erp_order_links',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('erp_system_code', sa.String(length=64), nullable=True),
    sa.Column('erp_order_no', sa.String(length=100), nullable=True),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_order_links_project_id'), 'erp_order_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_erp_order_links_tenant_id'), 'erp_order_links', ['tenant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_no', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('erp_ref_json', sa.JSON(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_project_id'), 'invoices', ['project_id'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_table('payment_plans',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('plan_no', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('trigger_milestone_code', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_plans_project_id'), 'payment_plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_payment_plans_tenant_id'), 'payment_plans', ['tenant_id'], unique=False)
    op.create_table('payment_records',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('matched_plan_id', sa.String(length=36), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_project_id'), 'payment_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_payment_records_tenant_id'), 'payment_records', ['tenant_id'], unique=False)
    op.create_table('renewal_opportunities',
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount_expect', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('close_date_expect', sa.Date(), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('related_asset_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renewal_opportunities_customer_id'), 'renewal_opportunities', ['customer_id'], unique=False)
    op.create_index(op.f('ix_renewal_opportunities_tenant_id'), 'renewal_opportunities', ['tenant_id'], unique=False)
    op.create_table('service_tickets',
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('ticket_no', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('ai_summary_json', sa.JSON(), nullable=True),
    sa.Column('assigned_to_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_tickets_customer_id'), 'service_tickets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_tickets_project_id'), 'service_tickets', ['project_id'], unique=False)
    op.create_index(op.f('ix_service_tickets_tenant_id'), 'service_tickets', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_tickets_tenant_id'), table_name='service_tickets')
    op.drop_index(op.f('ix_service_tickets_project_id'), table_name='service_tickets')
    op.drop_index(op.f('ix_service_tickets_customer_id'), table_name='service_tickets')
    op.drop_table('service_tickets')
    op.drop_index(op.f('ix_renewal_opportunities_tenant_id'), table_name='renewal_opportunities')
    op.drop_index(op.f('ix_renewal_opportunities_customer_id'), table_name='renewal_opportunities')
    op.drop_table('renewal_opportunities')
    op.drop_index(op.f('ix_payment_records_tenant_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_project_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_payment_plans_tenant_id'), table_name='payment_plans')
    op.drop_index(op.f('ix_payment_plans_project_id'), table_name='payment_plans')
    op.drop_table('payment_plans')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_project_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_erp_order_links_tenant_id'), table_name='erp_order_links')
    op.drop_index(op.f('ix_erp_order_links_project_id'), table_name='erp_order_links')
    op.drop_table('erp_order_links')
    op.drop_index(op.f('ix_delivery_milestones_tenant_id'), table_name='delivery_milestones')
    op.drop_index(op.f('ix_delivery_milestones_project_id'), table_name='delivery_milestones')
    op.drop_table('delivery_milestones')
    op.drop_index(op.f('ix_change_requests_tenant_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_project_id'), table_name='change_requests')
    op.drop_table('change_requests')
    # ### end Alembic commands ###
