"""add_cost_snapshots_table

Revision ID: bbcf1ebb7a0e
Revises: 73c17709cda6
Create Date: 2026-02-28 13:56:37.313069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbcf1ebb7a0e'
down_revision: Union[str, None] = '73c17709cda6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_snapshots',
    sa.Column('quote_version_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_type', sa.String(length=32), nullable=False),
    sa.Column('price_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('margin_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('line_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_snapshots_quote_version_id'), 'cost_snapshots', ['quote_version_id'], unique=False)
    op.create_index(op.f('ix_cost_snapshots_tenant_id'), 'cost_snapshots', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_snapshots_tenant_id'), table_name='cost_snapshots')
    op.drop_index(op.f('ix_cost_snapshots_quote_version_id'), table_name='cost_snapshots')
    op.drop_table('cost_snapshots')
    # ### end Alembic commands ###
