"""add_lead_code_column

Revision ID: c0d74316a046
Revises: 84f6130693d9
Create Date: 2026-02-28 16:36:47.374136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d74316a046'
down_revision: Union[str, None] = '84f6130693d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('lead_code', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_leads_lead_code'), 'leads', ['lead_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_lead_code'), table_name='leads')
    op.drop_column('leads', 'lead_code')
    # ### end Alembic commands ###
