"""phase2_project_quote_contract

Revision ID: e4bb22e47034
Revises: 116a971e52b1
Create Date: 2026-02-27 23:20:04.573902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4bb22e47034'
down_revision: Union[str, None] = '116a971e52b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_versions',
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('doc_attachment_id', sa.String(length=36), nullable=True),
    sa.Column('key_clauses_json', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_versions_contract_id'), 'contract_versions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_versions_tenant_id'), 'contract_versions', ['tenant_id'], unique=False)
    op.create_table('contracts',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('contract_no', sa.String(length=64), nullable=False),
    sa.Column('current_version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('amount_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payment_terms_json', sa.JSON(), nullable=True),
    sa.Column('delivery_terms_json', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_project_id'), 'contracts', ['project_id'], unique=False)
    op.create_index(op.f('ix_contracts_tenant_id'), 'contracts', ['tenant_id'], unique=False)
    op.create_table('opportunity_projects',
    sa.Column('project_code', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('stage_code', sa.String(length=16), nullable=False),
    sa.Column('amount_expect', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('close_date_expect', sa.Date(), nullable=True),
    sa.Column('competitors_json', sa.JSON(), nullable=True),
    sa.Column('key_requirements_json', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=2), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_projects_customer_id'), 'opportunity_projects', ['customer_id'], unique=False)
    op.create_index(op.f('ix_opportunity_projects_tenant_id'), 'opportunity_projects', ['tenant_id'], unique=False)
    op.create_table('project_stage_history',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('from_stage', sa.String(length=16), nullable=False),
    sa.Column('to_stage', sa.String(length=16), nullable=False),
    sa.Column('changed_by_id', sa.String(length=36), nullable=True),
    sa.Column('changed_by_name', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_stage_history_project_id'), 'project_stage_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_stage_history_tenant_id'), 'project_stage_history', ['tenant_id'], unique=False)
    op.create_table('quote_lines',
    sa.Column('quote_version_id', sa.String(length=36), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=16), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('spec', sa.String(length=300), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cost_est', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('leadtime_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_lines_quote_version_id'), 'quote_lines', ['quote_version_id'], unique=False)
    op.create_index(op.f('ix_quote_lines_tenant_id'), 'quote_lines', ['tenant_id'], unique=False)
    op.create_table('quote_versions',
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('price_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('margin_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('delivery_promise_date', sa.Date(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('terms_summary_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_versions_quote_id'), 'quote_versions', ['quote_id'], unique=False)
    op.create_index(op.f('ix_quote_versions_tenant_id'), 'quote_versions', ['tenant_id'], unique=False)
    op.create_table('quotes',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('quote_no', sa.String(length=64), nullable=False),
    sa.Column('current_version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_project_id'), 'quotes', ['project_id'], unique=False)
    op.create_index(op.f('ix_quotes_tenant_id'), 'quotes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_tenant_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_project_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_quote_versions_tenant_id'), table_name='quote_versions')
    op.drop_index(op.f('ix_quote_versions_quote_id'), table_name='quote_versions')
    op.drop_table('quote_versions')
    op.drop_index(op.f('ix_quote_lines_tenant_id'), table_name='quote_lines')
    op.drop_index(op.f('ix_quote_lines_quote_version_id'), table_name='quote_lines')
    op.drop_table('quote_lines')
    op.drop_index(op.f('ix_project_stage_history_tenant_id'), table_name='project_stage_history')
    op.drop_index(op.f('ix_project_stage_history_project_id'), table_name='project_stage_history')
    op.drop_table('project_stage_history')
    op.drop_index(op.f('ix_opportunity_projects_tenant_id'), table_name='opportunity_projects')
    op.drop_index(op.f('ix_opportunity_projects_customer_id'), table_name='opportunity_projects')
    op.drop_table('opportunity_projects')
    op.drop_index(op.f('ix_contracts_tenant_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_project_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_contract_versions_tenant_id'), table_name='contract_versions')
    op.drop_index(op.f('ix_contract_versions_contract_id'), table_name='contract_versions')
    op.drop_table('contract_versions')
    # ### end Alembic commands ###
