"""add_approval_flow_tables

Revision ID: f7d05d597e85
Revises: b946314d27fb
Create Date: 2026-02-28 13:46:56.300857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d05d597e85'
down_revision: Union[str, None] = 'b946314d27fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_flows',
    sa.Column('biz_type', sa.String(length=32), nullable=False),
    sa.Column('biz_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_node', sa.Integer(), nullable=False),
    sa.Column('total_nodes', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.String(length=36), nullable=True),
    sa.Column('submitted_by_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_flows_biz_id'), 'approval_flows', ['biz_id'], unique=False)
    op.create_index(op.f('ix_approval_flows_biz_type'), 'approval_flows', ['biz_type'], unique=False)
    op.create_index(op.f('ix_approval_flows_status'), 'approval_flows', ['status'], unique=False)
    op.create_index(op.f('ix_approval_flows_tenant_id'), 'approval_flows', ['tenant_id'], unique=False)
    op.create_table('approval_tasks',
    sa.Column('flow_id', sa.String(length=36), nullable=False),
    sa.Column('node_order', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.String(length=36), nullable=False),
    sa.Column('assignee_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.String(length=30), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_tasks_assignee_id'), 'approval_tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_approval_tasks_flow_id'), 'approval_tasks', ['flow_id'], unique=False)
    op.create_index(op.f('ix_approval_tasks_tenant_id'), 'approval_tasks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_tasks_tenant_id'), table_name='approval_tasks')
    op.drop_index(op.f('ix_approval_tasks_flow_id'), table_name='approval_tasks')
    op.drop_index(op.f('ix_approval_tasks_assignee_id'), table_name='approval_tasks')
    op.drop_table('approval_tasks')
    op.drop_index(op.f('ix_approval_flows_tenant_id'), table_name='approval_flows')
    op.drop_index(op.f('ix_approval_flows_status'), table_name='approval_flows')
    op.drop_index(op.f('ix_approval_flows_biz_type'), table_name='approval_flows')
    op.drop_index(op.f('ix_approval_flows_biz_id'), table_name='approval_flows')
    op.drop_table('approval_flows')
    # ### end Alembic commands ###
